name: arweave
description: ""
version: 3.5.1
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cryptography: ^2.0.1
  http: ^0.13.3
  json_annotation: ^4.0.1
  jwk: ^0.1.0
  meta: ^1.7.0
  pointycastle: ^3.1.1
  built_value: ^8.0.6
  js: ^0.6.3
  retry: ^3.1.0
  base32: ^2.1.1
  async: ^2.9.0
  mutex: ^3.0.1

dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^6.1.4
  lints: ^1.0.1
  test: ^1.17.8
